Repository TEAM-8ight/modu-todo, pull requests merged in 2021-08, with the labels that each got.

#20 [#19] feat: Theme 컬러 설정
  src/styles/Theme.ts
Labels: style

#16 Feature/todo context
  src/App.tsx
  src/context/todoContext/TodoContext.tsx
  src/context/todoContext/actionCreators.ts
  src/context/todoContext/actionTypes.ts
  src/context/todoContext/reducer.ts
  src/index.tsx
  src/types/context.ts
  src/types/index.ts
  src/types/todo.ts
  src/utils/contants.ts
  src/utils/index.ts
  src/utils/localStorageHelper.ts
Labels: enhancement

#22 Feature/dropdown
  src/App.tsx
  src/assets/svg/calendar.svg
  src/assets/svg/circle-plus.svg
  src/assets/svg/delete.svg
  src/assets/svg/down-arrow.svg
  src/assets/svg/edit.svg
  src/assets/svg/etc.svg
  src/assets/svg/exercise.svg
  src/assets/svg/high.svg
  src/assets/svg/life.svg
  src/assets/svg/low.svg
  src/assets/svg/middle.svg
  src/assets/svg/study.svg
  src/assets/svg/up-arrow.svg
  src/assets/svg/work.svg
  src/components/common/Dropdown.tsx
  src/components/temp/DropdownTemp.tsx
  src/context/todoContext/actionCreators.ts
  src/context/todoContext/mockData.ts
  src/context/todoContext/reducer.ts
  src/styles/Theme.ts
  src/types/context.ts
  src/types/index.ts
  src/types/todo.ts
  src/utils/contants.ts
  src/utils/getRandomEnum.ts
  src/utils/hooks/index.ts
  src/utils/hooks/useDetectOutsideClick.ts
  src/utils/index.ts
  src/utils/localStorageHelper.ts
Labels: enhancement

#25 Feature/header
  package-lock.json
  src/App.tsx
  src/assets/svg/modu-todo.svg
  src/components/TodoHeader/TodoHeader.tsx
Labels: enhancement

#26 Feature/filter
  src/App.tsx
  src/components/TodoFilter/TodoFilter.tsx
  src/components/common/FilterButton.tsx
  src/context/todoContext/TodoContext.tsx
  src/context/todoContext/actionCreators.ts
  src/context/todoContext/actionTypes.ts
  src/context/todoContext/reducer.ts
  src/styles/Theme.ts
  src/types/context.ts
  src/types/filter.ts
  src/types/index.ts
  src/types/todo.ts
Labels: enhancement, style
